version: '3'

services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped