version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - WEBPUSH_PUBLIC_KEY=${WEBPUSH_PUBLIC_KEY}
      - WEBPUSH_PRIVATE_KEY=${WEBPUSH_PRIVATE_KEY}
      - WEBPUSH_MAIL=${WEBPUSH_MAIL}
      - BREVO_USERNAME=${BREVO_USERNAME}
      - BREVO_PASSWORD=${BREVO_PASSWORD}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - MY_JWT_SECRET=${MY_JWT_SECRET}
      - PYTHON_SCRAPER_URL=${PYTHON_SCRAPER_URL}
      - PYTHON_SCRAPER_SECRETKEY=${PYTHON_SCRAPER_SECRETKEY}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: