version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/Scraper?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=!grea8One12345
      - JWT_SECRET=LxgKD32LseXHuPq8VMs3yYFNLadudQ53YUn4
      - WEBPUSH_PUBLIC_KEY=BLzc_LUkNVhLWv-8lDqgpG2yPMWCxZb6h5SFSqvK-_rt3P-UxXg9AUra1Vy-tM6hudJNqHGR4L-__H5X6Sssp88
      - WEBPUSH_PRIVATE_KEY=Sn_z2AAo6qYs_PActNrzyWWE4VkAWhiLQwpwsF5kgx8
      - WEBPUSH_MAIL=mailto:rajsudhanshu9431@gmail.com
      - BREVO_USERNAME=7e5cbc001@smtp-brevo.com
      - BREVO_PASSWORD=gbFBSfRj7qwskxH6
      - CLOUDINARY_URL=cloudinary://197768488225743:PD_wKvRGydGmcLpNxZcyDbPbNaM@duscp44oq
      - MY_JWT_SECRET=LxgKD32LseXHuPq8VMs3yYFNLadudQ53YUn4
      - PYTHON_SCRAPER_URL=http://host.docker.internal:8000
      - PYTHON_SCRAPER_SECRETKEY=AIzaSyDV7niwpxyplcLiimbmA-5idmj0gVmfo14
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=!grea8One12345
      - MYSQL_DATABASE=Scraper
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: