spring.application.name=SCRAPER_BKD_SECURITY
server.port=8081

server.max-http-header-size=16384

spring.datasource.password=!grea8One12345
spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/scraper?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=update


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=1

logging.file.name=logs/app.log

# Log level 
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.org.scraper_bkd_security=DEBUG

# Log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile,openid
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri= https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo


